### PR TITLE
Watchman Updates

### PR DESCRIPTION
**Pull request by BenLand100**
This switches Watchman's default PMT to the 10" R7081 (which was improved in this pull request), and includes various bugfixes for simulation/analysis.

Notable changes:
* R7081 has proper Q/T simulation based on Hamamatsu specs (Will switch to the R7081 measurements in #22 when it gets merged)
* Adds a processor ```watchmandaq``` which for now is a clone of ```simpledaq``` but uses hit times including transit time spread (as opposed to ```simpledaq``` reporting raw monte-carlo hit time).
* Improves ```WatchmanDetectorFactory``` to read defaults from a table ```WATCHMAN_PARAMS``` instead of requiring user to specify at macro level in ```DETECTOR``` table
* ```WatchmanDetectorFactory``` defaults to 30% photocathode coverage 2% veto coverage
* ```PDFPMTTime``` now returns offsets + given time instead of just offsets (bugfix)
* The steel material was not opaque... (much head bashing to find this was the problem) switched to stainless_steel since that is both more appropriate and opaque

### CODE REVIEW

**Comment by mastbaum** [comment]
@BenLand100 what would you say to changing `simpledaq` to use the front-end time, rather than adding a new DAQ processor? I think it makes more sense for even `simpledaq` to include the TTS; it's supposed to be simple but still somewhat realistic.

**Comment by BenLand100** [comment]
It makes no difference to me if that seems more appropriate. I was thinking that Watchman would eventually want its own DAQ processor but that is perhaps jumping the gun a bit.

**Comment by mastbaum** [comment]
Okay, I'd prefer changing `simpledaq` for now then since it will make that more useful for everyone.

**Comment by mastbaum** [comment]
Looks good to me, though I wonder why the transit time distribution is centered on zero. The offset could be absorbed into the cable delay, but in the current case with no cable delay we end up with some front-end times earlier than photon hit times, which seems strange:
hittimes

**Comment by orebi** [comment]
We could decide to introduce an arbitrary offset, but to be fair I don't think it matters a great deal: the only thing that really matters here is intra-event timing, and inter-event timing, both of which I think should be OK as is.

Thought now I'm curious: do we just have a Gaussian distribution for the TTS?  We don't seem to have e.g. pre-pulsing.  In which case, what is the tail at late times?  (If it's noise hits then we should see it at early times too.)

**Comment by mastbaum** [comment]
Not totally arbitrary, since transit times are >0 and measurable for a given PMT, distinct from cable delay. This currently has photons being detected before they possibly could have arrived, and while (as you point out) absolute timing isn't so interesting, it seems easy enough to get it right.

The TT distribution here indeed appears to be Gaussian with sigma=1.8 ns:
tts

The late tail is due to reflections from the PMTs. Here it with the non-reflective "black bucket" model:
norefl

**Comment by BenLand100** [comment]
The thinking here for not including the transit time in the PDF was that we currently don't have a DAQ that will correct for time offsets and the transit time for these big PMTs is 50ns. If we're not concerned with absolute time, I can add the transit time into the PDF for correctness (oddly this argument works both ways...). This distribution is intended to "match" hamamatsu specifications, and they only quote a transit time and transit time spread -> a gaussian. #22 had the measured distributions.

**Comment by mastbaum** [comment]
Fair enough, merging.

**Pull request merged**
