### PR TITLE
cpgrantDev

### PR DESCRIPTION
**Pull request by cpgrant2482**
Two new detector factory files, a data directory with associated ratdb files, and example visualization macros were created to allow the construction of an isotope-filled balloon in Theia.

### CODE REVIEW

**Comment by jcaravaca** [comment]
Thanks @cpgrant2482. Could you put your 'visualize_theia' macro in a dedicated folder. It'd be better to keep things tidy. I'll merge after that.

**Comment by mastbaum** [comment]
Hi @cpgrant2482 @jcaravaca, in trying to run physics simulations, I am running into some trouble with:

- [ ] **Detector factory not registered**

```
DB: Setting DETECTOR[] experiment to Theia_0vbb
DB: Setting DETECTOR[] detector_factory to Theia_0vbb
Loading experiment-specific RATDB files for: Theia_0vbb
DB: Loading /<...>/rat-pac/data/Theia_0vbb/MATERIALS.ratdb ... Success!
DB: Loading /<...>/rat-pac/data/Theia_0vbb/OPTICS.ratdb ... Success!
DB: Loading /<...>/rat-pac/data/Theia_0vbb/THEIA_PARAMS.ratdb ... Success!
Loading detector factory Theia_0vbb
No detector factory registered as "Theia_0vbb"
```
This is fixed by the following patch:
```diff
diff --git a/src/geo/DetectorConstruction.cc b/src/geo/DetectorConstruction.cc
index b84ec28..1661e27 100644
--- a/src/geo/DetectorConstruction.cc
+++ b/src/geo/DetectorConstruction.cc
@@ -17,6 +17,7 @@
 #include <RAT/DetectorFactory.hh>
 #include <RAT/WatchmanDetectorFactory.hh>
 #include <RAT/TheiaDetectorFactory.hh>
+#include <RAT/Theia0vbbDetectorFactory.hh>

 using namespace std;

@@ -27,6 +28,7 @@ DetectorConstruction* DetectorConstruction::sDetectorConstruction = NULL;
 DetectorConstruction::DetectorConstruction() {
     DetectorFactory::Register("Watchman",new WatchmanDetectorFactory());
     DetectorFactory::Register("Theia",new TheiaDetectorFactory());
+    DetectorFactory::Register("Theia_0vbb",new Theia0vbbDetectorFactory());
 }

 G4VPhysicalVolume* DetectorConstruction::Construct() {
```

- [ ] **Balloon material `evoh` not defined**

```
-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : GeomMgt0002
      issued by : G4Region::ScanVolumeTree()
Logical volume <balloon>
does not have a valid material pointer.
A logical volume belonging to the (tracking) world volume must have a valid material.Check your geometry construction.

*** Fatal Exception *** core dump ***
-------- EEEE -------- G4Exception-END --------- EEEE -------


*** G4Exception: Aborting execution ***
Aborted (core dumped)
```
with
```
{
name: "GEO",
index: "balloon"
valid_begin: [0,0],
valid_end: [0,0],
mother: "detector",
type: "sphere",
r_max: 6500.0,
r_min: 0.0,
position: [0.0, 0.0, 0.0],
material: "evoh",
color: [0.8, 0.9, 0.9, 0.1],
drawstyle: "solid"
}
```
in `data/Theia_0vbb/Theia_0vbb.geo`.

- [ ] **PMTs not constructed?**

I haven't fully investigated this yet, but the geometry initializes very quickly relative to the `Theia` detector factory (~1 second vs. 20 minutes), and event simulation is similarly fast (0.01 s vs. 60 s), then events have 0 or occasionally 1 detected photoelectrons (compared to ~1200).

**Comment by cpgrant2482** [comment]
Hi @mastbaum, I haven't looked at the code for a while but I can try this weekend.  Classes started and I'm stuck writing my lectures at the moment.

**Comment by mastbaum** [comment]
> **PMTs not constructed?**

Found the isssue in `data/Theia_0vbb/THEIA_PARAMS.ratdb`: `photocathode_coverage: 0.01`.

So the only remaining issue is the missing definition for the `evoh` material (balloon). @cpgrant2482 do you have measurements for this? Would it be close enough if I just substituted UVT acrylic?

/cc @vlozza

**Comment by vlozza** [comment]
Great!
Can't we use nylon as material?

**Comment by cpgrant2482** [comment]
Thanks for finding this Andy!  I think I was drawing the visualization at one point, and of course I didn't want to wait for all the PMTs to be drawn.  I set the coverage really low to accomplish that.

Technically, EVOH is really a dummy material right now since I don't know any of the OPTICS parameters.  I did a literature search a while back and came up with nothing.  In KamLAND we had alternating layers of nylon (for strength) and EVOH (very low radon permeability).  I think we assumed the optical parameters were very similar and were able to achieve a reasonable MC/data comparison of the detector response in KamLAND without simulating the balloon altogether.  100% nylon could just be used instead.

You can alternate the radius and thickness of the material as desired using a ratdb script.

**Comment by mastbaum** [comment]
We've got the nylon defined [here](https://github.com/rat-pac/rat-pac/blob/master/data/OPTICS.ratdb#L783), but it looks very approximate (just a sharp cutoff in absorption between 300-330 nm). Probably want to use a more plausible model for this since it will affect the light yield. I'll see if I can dig anything up for nylon, unless someone already has references.

**Comment by vlozza** [comment]
I can ask Lindley if she has the optical properties of nylon

**Pull request merged**
