### PR TITLE
Update fastjson.

### PR DESCRIPTION
**Pull request by BenLand100**
Fixes rat-pac issue #47 . The parser will now throw a parser_error whenever a malformed number is found. Previously atoi and atof made a 'best effort' to parse a number, and discarded any errors, so e.g. 1.2-3 would get parsed to 1.2 while this input would now result in an error.

Also fixes json compliance of output and adds Beta™ support for 64bit integer types.

### CODE REVIEW

**Comment by BenLand100** [comment]
Example output from the (now corrected) malformed number. 
```
RAT, version e1bb806
Status messages enabled: info 
Hostname: blandtop PID: 22871
DB: Loading /home/benland100/research/watchman/rat-pac/data/DAQ.ratdb ... Success!
DB: Loading /home/benland100/research/watchman/rat-pac/data/DETECTOR.ratdb ... Success!
DB: Loading /home/benland100/research/watchman/rat-pac/data/ELEMENTS.ratdb ... Success!
DB: Loading /home/benland100/research/watchman/rat-pac/data/IBD.ratdb ... Success!
DB: Loading /home/benland100/research/watchman/rat-pac/data/IO.ratdb ... Success!
DB: Loading /home/benland100/research/watchman/rat-pac/data/MATERIALS.ratdb ... Success!
DB: Loading /home/benland100/research/watchman/rat-pac/data/MC.ratdb ... Success!
DB: Loading /home/benland100/research/watchman/rat-pac/data/NOISE.ratdb ... Success!
DB: Loading /home/benland100/research/watchman/rat-pac/data/NTUPLE.ratdb ... Success!
terminate called after throwing an instance of 'json::parser_error'
  what():  [708:24] Malformed real
DB: Loading /home/benland100/research/watchman/rat-pac/data/OPTICS.ratdb ... Aborted
```

**Comment by mastbaum** [comment]
@BenLand100 was this ever actually merged?

**Comment by BenLand100** [comment]
Looks like it was not - json.h still has references to atof and atoi. I could open a PR with just this update, but it is included in #37. It's been a while and I'm not sure what we want to do with #37

**Comment by mastbaum** [comment]
Ah, ok. I'd support merging #37 if you think it's good to go. Would it be much trouble to give it a quick test, just in case some relevant interface has changed?

**Pull request closed without merging**
