### PR TITLE
Internal PMT handling improvements + Watchboy geometry

### PR DESCRIPTION
**Pull request by BenLand100**
Ultimately this is working towards making PMT placement in geometries more flexible than requiring a single PMTINFO table (WATCHBOY geometry needs this). The geometry code already handles the placement, this code is to get that information into Gsim and by extension the DS. As a side effect Gsim will be able to use the proper charge and time models per PMT model even if multiple types of PMTs exist in the geometry as evidently originally intended.

Notable changes (so far):
* Gsim pulls PMTInfo directly from PMTs built in the current geometry, no longer from a single ```PMTINFO``` table
* PMTs represented internally by an continuous ```ID``` in an array that are not guaranteed to be the same if after modifications to the geometry when using multiple tables (will cross this bridge if it is ever an issue)
* PMTInfo (in DS) keeps track of ```pmt_model``` for Gsim (previously ```pmt_type``` but renamed since there is another quantity called ```type``` associated with PMTs) 
* Gsim handles charge/time for different PMT models separately and automatically based on built geometry
* Makes PDFPMTTime and PDFPMTCharge behave similarly to avoid confusion.
* PMT positions are always in global coordinates -> calculate local coordinates in GeoPMTFactoryBase for placement
* Includes preliminary Watchboy geometry

Potentially ready for a merge.

### CODE REVIEW

**Comment by BenLand100** [comment]
@mastbaum is there an easy way to see what the docs will look like without merging? My fallback would be to setup a rtfd page pointed at my fork, if nothing else works.

**Comment by mastbaum** [comment]
Yep, install [Sphinx](http://sphinx.pocoo.org) if you don't have it already -- you can just `pip install sphinx` -- then inside `doc,` type `make html`.

**Comment by BenLand100** [comment]
Addition of ``PMTID`` would lead to confusion in the DS, and unnecessary redundancy for most cases, so decided against it. The continuous ``ID`` of the PMT will work in virtually all circumstances (analogous to previous behavior), and the ``type`` can be used to single out individual PMTs or functional groups of PMTs independent of the ``ID``

**Comment by orebi** [comment]
Are you suggesting only storing the continuous index in the DS?  I do think we want to be able to identify PMTs using whatever PMTID is used on an experiment.  My own feeling is that the index, which is basically just internal to RAT, is less useful to store than the ID.

**Comment by BenLand100** [comment]
Not exactly - I'm suggesting avoiding using two quantities in the first place, i.e. preserve old functionality of ```PMTID``` == ```ID``` == ```Index``` (historically called ```ID```). This requires the same forethought as before of ensuring the order of PMTs in the array corresponds to some physical PMT numbering system, which is a little rigid, but I think less confusing than having two numbers to identify any particular PMT. At the code level it only makes sense for RAT to store its internal index (guaranteed to be unique) in the DS, so to ensure this corresponds to some physical number it is easiest to require the internal index simply be the same as the physical numbers.

**Comment by BenLand100** [comment]
The tl;dr on this is that a logical separation between internal Index and physical PMTID is (most likely) not a critical item and would take a fair amount of work to achieve, whereas preserving previous functionality with these other improvements already works.

**Pull request merged**
