### PR TITLE
Reactor ibd

### PR DESCRIPTION
**Pull request by pershint**
Pull request for the Reactor Inverse Beta Decay generator.  The generator selects an initial antineutrino energy based on the parameterized neutrino flux from reactors.  Using this energy, the positron and neutron energies are found and generated.  The distribution that antineutrino energies are chosen from can also be modified by manually inputting reactor isotopic contents as shown in the ReacIBD_demo_watchman.mac file.  A read-me must still be written for usage of the generator.

~Teal Pershing

### CODE REVIEW

**Comment by mastbaum** [comment]
Thanks, Teal, this looks great! Would you mind also adding a short description to the generator documentation in `doc`?

**Comment by pershint** [comment]
Sure thing!  Should I just add the description and do another pull request
then?

Best,
~Teal

On Sunday, July 19, 2015, Andy Mastbaum <notifications@github.com> wrote:
> Thanks, Teal, this looks great! Would you mind also adding a short
description to the generator documentation in doc?
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci4.googleusercontent.com/proxy/AViMylTiEl3BihWldBfFnI_ubcKxwpog-0cOQCD-28CNMAaiaT8DffcoB9A9m_sMMFw-s2xBYfGfeNricbjX8T1PKchXgv6UtwtUVXZc9GETxAjVdt-bCBZzwemhCcTuq_3fWsd0X0Hf6unjmzg0c_U2peaWBQ=s0-d-e1-ft#https://github.com/notifications/beacon/AHm98Bld3OgfyYDlio64HDO2dPqq3gVYks5oe8YigaJpZM4Fbadg.gif
>

**Comment by mastbaum** [comment]
@pershint, if you commit the documentation and push to this same branch `ReactorIBD`, that will update this pull request, so no need for a new one.

**Comment by pershint** [comment]
Hi Andy,

I just completed modifying the generators documentation to include the
ReactorIBD description.  I committed and pushed changes, so they should be
on the pull request.

Let me know if you see anything else to modify.  Thank you!
~Teal Pershing

**Comment by mastbaum** [comment]
Thanks for the docs! I tested the generator and all worked well for me.

I did get one error with my compiler (Apple clang-600.0.57) though:
``` 
src/gen/ReacIBDgen.cc:19:14: error: unused variable 'GFERMI'
      [-Werror,-Wunused-const-variable]
const double GFERMI = 1.16639e-11 / MeV / MeV;
             ^
1 error generated.
```
Looks to work with that commented out; could you update to comment/remove?

**Comment by mastbaum** [comment]
Hi, @pershint, I can just merge this PR then remove that line, if that's easier.

**Comment by pershint** [comment]
Hi Andy,

Sorry I haven't replied!  That was a constant from another generator that
did not get deleted.  Either commenting or removing should cause no
problems.

If that is okay with you, that would be great.  Thanks for following up
with me again!

Best,
~Teal Pershing

On Friday, August 21, 2015, Andy Mastbaum <notifications@github.com> wrote:
> Hi, @pershint, I can just merge this PR then remove that line, if that's
easier.
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci5.googleusercontent.com/proxy/XuHuczaoRltM7hH2pz4X3_w0XKqfUSFTDE9Zx79ptH12LjfL5aRr_5yxjOUUjXd1ikMa5iSFYLPkkZohGFhy5Gn5SK08xzVmEPTgMwignQ0Zv60qRDKLncr6XuvD0PBm1RK8uDooHipYZlmZ4nvF4ignui2Puw=s0-d-e1-ft#https://github.com/notifications/beacon/AHm98IHxA9Ej8kBYR3KZInQ1IlZreK5zks5opxwqgaJpZM4Fbadg.gif
>

**Comment by mastbaum** [comment]
Thanks! Will merge this and then push the minor edits.

**Pull request merged**
