### PR TITLE
PMT Improvements.

### PR DESCRIPTION
**Pull request by BenLand100**
~~Still working on docs~~, but so people can check out the changes and comment:
- Breaks PMT build code into abstractable chunks instead of one big method in GeoPMTFactoryBase
  - Moved pmt code into a sub directory of geo
  - Removed Geo prefix from most PMT classes
  - Renamed and restructured some classes (e.g. PMT[Info]Parser)
  - PMTConstruction is now abstract
    - ToroidalPMTConstruction contains original PMT building code
    - RevolutionPMTConstruction for building PMTs as solid of revolution
- Adds individual PMT efficiency correction array to PMTINFO tables
  - Changes to database to allow manipulating array fields from macros
    - Get/set arrays as well as indexes in array
    - `/rat/db/set NAME[index] field[0] "first entry in 'field' field in NAME[index]"`
    - Templated Get/Set on everything but DBLinkPtr since DBLinkPtr needs explicit methods for python
    - Removed table size tracking because A) it didn't really work B) constructors ignored it C) prevented easy templating. If we want this functionality I'll make fastjson give the exact binary size of the data, but obviously this is not the same as the json-encoded size which is probably more relevant (and not what was stored before anyway)
    - Trivial to add support for boolean fields, so did that too.
  - BEfficiencyCorrection had similar functionality (does the B code work? could find no docs on it) so converted simply to EfficiencyCorrection to be more general
  - GLG4PMTOpticalModel kept a vector of pairs for some reason -> map
- Possible physics relevant changes
  - Original PMT code was not placing optical surface for photocathode correctly when placed without envelope, and fixing it likely changed transmission into PMT a bit
  - GLG4PMTOpticalModel did not need the optical surface of the photocathode, just the optical properties. Switched to optical properties (fix for previous point constructing surface too early)
  - GLG4PMTSD was doing nothing but calling a method with the exact same args and keeping data that was never used elsewhere. The information it needed on PMTs was bad for abstraction, so I removed it completely and put its functionality in GLG4PMTOpticalModel. Do people use the GLG4PMTSD for anything anymore, or was it just an artifact?
- Misc modifications throughout to accommodate new code

### CODE REVIEW

**Comment by BenLand100** [comment]
Worth noting that the revolution PMTs do initialize faster than toroidal PMTs by about a factor of two, but the simulation time is slightly slower in the revolution PMTs. Unsure if this is a geometric effect or not, as I discovered that the Torus PMTs parameters (shamelessly borrowed from snoplus rat) are at best rough approximations of the actual PMT shape, while I used the Hammatsu spec and local measurements of some R7081s to make the revolution PMT. Shown on left is the revolution PMT as GEANT4 sees it and on right is the torus PMT, both supposedly R7081s. (Note that the faceted nature of the visualization on the right is only visualization - the surface on the right is analytical torus segments, and on the left are flat approximate surfaces)
R7081s

**Comment by BenLand100** [comment]
This should be good to go, but we should discuss on the next call.

**Comment by BenLand100** [comment]
@mastbaum continuing from the discussion on #49 - I believe @jcaravaca (CHESS) and @bonventre (Theia sims) have been using code based off this approximately since its inception, and I don't think they've found any issues, so it should be fine to merge as-is. I can make some time to do a quick electron simulation tomorrow to double check.

**Comment by BenLand100** [comment]
@mastbaum I didn't encounter any issues testing this out just now, so all is good from my end.

**Comment by mastbaum** [comment]
Great, thanks for checking @BenLand100!

**Pull request merged**
